defaults:
  - _self_

bucket_model:
  num_buckets: 2
  temperature: 1.0
  sbert_model: "sentence-transformers/all-MiniLM-L6-v2"
  prototype_ema_decay: 0.5
  prototype_margin: 0.3
  prototype_eps: 1e-6
  entropy_weight: 1.0
  balance_weight: 1.0
  prototype_pull_weight: 1.0
  prototype_repulsion_weight: 1.0
  lr: 1e-3
  weight_decay: 0.0
  grad_clip: 1.0
  tree_depth: 1
  d_model: null  # set at runtime from dataset

train:
  eval_only: False
  eval_epoch: True
  epochs: [5,5,5]
  validate_every: 1
  log_interval: 50
  checkpoint: "bucket_model.pth"

data:
  rebuild_ds: False
  train:
    dataset: "wikiann"
    config: "en"
    batch_size: 16
    num_workers: 0
    subset: 1.0
    shuffle: True
  eval:
    dataset: "wikiann"
    config: "en"
    split: "validation"
    batch_size: 16
    num_workers: 0
    subset: 1.0
    shuffle: False
  dev:
    dataset: null
    config: null
    split: "test"
    batch_size: 16
    num_workers: 0
    subset: 1.0
    shuffle: False

runtime:
  num_threads: 8
  device: "cuda"

array: 0

dora:
  exclude: ["eval.*", "data.rebuild_ds", "logging.*"]

slurm:
  partition: "boost_usr_prod"
  gpus: 1
  mem_per_gpu: 32
  time: 120
  cpus_per_gpu: 8
  setup:
    - "module load python/3.11.7"
    - "source /leonardo/home/userexternal/slusetti/MoE/.venv/bin/activate"
    - "export SLURM_CPU_BIND=none"
    - "export HF_HOME=/leonardo_work/IscrC_LUSE/slusetti/hf-cache"
    - "export HF_DATASETS_CACHE=$HF_HOME/datasets"
    - "export TRANSFORMERS_CACHE=$HF_HOME/transformers"
    - "export HF_MODULES_CACHE=$HF_HOME/modules"
    - "export HF_HUB_CACHE=$HF_HOME/hub"
    - "export HUGGINGFACE_HUB_CACHE=$HF_HOME/hub"
    - "export HF_HUB_OFFLINE=1"
    - "export TRANSFORMERS_OFFLINE=1"
    - "export HF_DATASETS_OFFLINE=1"
